version: '3.5'

services:
    app:
        build: ./docker/images/php81
        volumes:
            - ./application:/app
        ports:
            - "6969:8000"
        networks:
            - cluster
        depends_on: # Remove in prod
            db-local:
                condition: service_healthy
                restart: true


    db-local:
        image: mysql:9.6.0
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -ptest"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 10s
        environment:
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: test
            MYSQL_CHARSET: utf8mb4
            MYSQL_COLLATION: utf8mb4_unicode_ci
        expose:
            - "3306"
        networks:
            - cluster

networks:
    cluster:
        name: cluster
        external: true
        driver: bridge

